from pathlib import Path
import sys
# v7: manual ElevenReader Copy triggers clipboard capture; normal Gmail selection remains unchanged.
root=Path(sys.argv[1] if len(sys.argv)>1 else '.')
p=root/'app/src/main/java/lt/skarda/dualtranslate/SelectionTranslateService.java'
s=p.read_text()
s=s.replace('import android.content.Intent;\n','import android.content.Intent;\nimport android.content.ClipboardManager;\n')
s=s.replace('    private long lastPollDiagnosticAt;\n','    private long lastPollDiagnosticAt;\n    private ClipboardManager clipboardManager;\n    private ClipboardManager.OnPrimaryClipChangedListener clipboardListener;\n    private long clipboardCaptureCooldownUntil;\n    private String lastForegroundPackage = "";\n')
s=s.replace('        wm = (WindowManager) getSystemService(WINDOW_SERVICE);\n        saveDiagnostic("v6 service connected. Standard Android selection is unchanged. ElevenReader toolbar polling is active even when ElevenReader sends no accessibility events.");\n        startElevenReaderPolling();\n','''        wm = (WindowManager) getSystemService(WINDOW_SERVICE);\n        clipboardManager = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);\n        clipboardListener = () -> handler.postDelayed(this::handleClipboardChanged, 60);\n        if (clipboardManager != null) clipboardManager.addPrimaryClipChangedListener(clipboardListener);\n        saveDiagnostic("v7 service connected. Gmail uses normal Android selection. In ElevenReader: select text, then tap Copy; clipboard change triggers translation.");\n''')
s=s.replace('        if (pkg.equals(getPackageName())) return;\n\n        int type = event.getEventType();','        if (pkg.equals(getPackageName())) return;\n        if (!pkg.isEmpty()) lastForegroundPackage = pkg;\n\n        int type = event.getEventType();')
needle='''        if (type == AccessibilityEvent.TYPE_WINDOW_CONTENT_CHANGED ||\n                type == AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED ||\n                type == AccessibilityEvent.TYPE_WINDOWS_CHANGED ||\n                type == AccessibilityEvent.TYPE_VIEW_CLICKED) {\n'''
repl='''        if (type == AccessibilityEvent.TYPE_VIEW_CLICKED && isElevenReader && isCopyEvent(event)) {\n            saveDiagnostic("v7: ElevenReader Copy click accessibility event detected. Waiting for clipboard update.");\n            handler.postDelayed(this::handleClipboardChanged, 100);\n            return;\n        }\n\n        if (type == AccessibilityEvent.TYPE_WINDOW_CONTENT_CHANGED ||\n                type == AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED ||\n                type == AccessibilityEvent.TYPE_WINDOWS_CHANGED ||\n                type == AccessibilityEvent.TYPE_VIEW_CLICKED) {\n'''
s=s.replace(needle,repl)
insert='''    private boolean isCopyEvent(AccessibilityEvent event) {\n        if (event == null) return false;\n        try {\n            AccessibilityNodeInfo src = event.getSource();\n            if (src != null) {\n                CharSequence t = src.getText();\n                CharSequence d = src.getContentDescription();\n                if (t != null && "copy".equalsIgnoreCase(t.toString().trim())) return true;\n                if (d != null && "copy".equalsIgnoreCase(d.toString().trim())) return true;\n            }\n            for (CharSequence cs : event.getText()) if (cs != null && "copy".equalsIgnoreCase(cs.toString().trim())) return true;\n        } catch (Exception ignored) {}\n        return false;\n    }\n\n    private void handleClipboardChanged() {\n        long now = SystemClock.uptimeMillis();\n        if (now < clipboardCaptureCooldownUntil) return;\n        String activePackage = lastForegroundPackage;\n        try {\n            AccessibilityNodeInfo root = getRootInActiveWindow();\n            if (root != null && root.getPackageName() != null) activePackage = root.getPackageName().toString();\n        } catch (Exception ignored) {}\n        if (!ELEVEN_READER_PACKAGE.equals(activePackage)) return;\n        clipboardCaptureCooldownUntil = now + 1500;\n        saveDiagnostic("v7: clipboard changed while ElevenReader is active. Capturing copied phrase for LT + RU translation.");\n        handler.postDelayed(this::launchClipboardCapture, 70);\n    }\n\n'''
s=s.replace('    private void startElevenReaderPolling() {',insert+'    private void startElevenReaderPolling() {')
s=s.replace('''    public void onDestroy() {\n        INSTANCE = null;\n''','''    public void onDestroy() {\n        INSTANCE = null;\n        try { if (clipboardManager != null && clipboardListener != null) clipboardManager.removePrimaryClipChangedListener(clipboardListener); } catch (Exception ignored) {}\n''')
p.write_text(s)

b=root/'app/build.gradle'
t=b.read_text().replace("applicationId 'lt.skarda.dualtranslate.v6'","applicationId 'lt.skarda.dualtranslate.v7'").replace('versionCode 6','versionCode 7').replace("versionName '6.0'","versionName '7.0'")
b.write_text(t)
for fp in ['app/src/main/AndroidManifest.xml','app/src/main/res/values/strings.xml','app/src/main/java/lt/skarda/dualtranslate/MainActivity.java','app/src/main/java/lt/skarda/dualtranslate/TextReceiverActivity.java']:
    q=root/fp; z=q.read_text().replace('Dual Translate v6','Dual Translate v7'); q.write_text(z)
q=root/'app/src/main/java/lt/skarda/dualtranslate/ClipboardCaptureActivity.java'
q.write_text(q.read_text().replace('ElevenReader automatic Copy fallback','ElevenReader manual Copy trigger'))
