from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else '.')
svc = root/'app/src/main/java/lt/skarda/dualtranslate/SelectionTranslateService.java'
s = svc.read_text()
s = s.replace('import android.content.SharedPreferences;\n', 'import android.content.SharedPreferences;\nimport android.content.Intent;\n')
s = s.replace('    private static final int MAX_SELECTED_CHARS = 2000;\n', '    private static final int MAX_SELECTED_CHARS = 2000;\n    private static final String ELEVEN_READER_PACKAGE = "io.elevenlabs.readerapp";\n')
s = s.replace('    private long shareFallbackAfter;\n', '    private long shareFallbackAfter;\n    private long elevenReaderSeenUntil;\n    private long elevenToolbarFirstSeen;\n    private long copyFallbackCooldownUntil;\n')
s = s.replace('        long now = SystemClock.uptimeMillis();\n\n        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {', '        long now = SystemClock.uptimeMillis();\n        boolean isElevenReader = ELEVEN_READER_PACKAGE.equals(pkg);\n        if (isElevenReader) elevenReaderSeenUntil = now + 9000;\n\n        if (type == AccessibilityEvent.TYPE_VIEW_TEXT_SELECTION_CHANGED) {')
s = s.replace('        if (type == AccessibilityEvent.TYPE_TOUCH_INTERACTION_END) {\n            handler.postDelayed(this::scanActiveWindowForSelection, 100);\n            handler.postDelayed(this::scanForSelectionUi, 140);\n            return;\n        }', '        if (type == AccessibilityEvent.TYPE_TOUCH_INTERACTION_END) {\n            handler.postDelayed(this::scanActiveWindowForSelection, 100);\n            handler.postDelayed(this::scanForSelectionUi, 140);\n            if (isElevenReader) {\n                handler.postDelayed(this::scanForSelectionUi, 320);\n                handler.postDelayed(this::scanForSelectionUi, 620);\n                handler.postDelayed(this::scanForSelectionUi, 900);\n            }\n            return;\n        }')
needle = '''        AccessibilityNodeInfo dual = findNode(root, "Dual Translate", true);\n        if (dual == null) dual = findNode(root, "Dual Translate v2", true);\n        if (dual != null) {\n            if (clickNodeOrParent(dual)) {\n                actionCooldownUntil = now + 3200;\n                saveDiagnostic("Automatic selected-text action: clicked Dual Translate. Waiting for Android to deliver the selected phrase.");\n                return true;\n            }\n        }\n\n'''
insert = '''        AccessibilityNodeInfo dual = findNode(root, "Dual Translate", true);\n        if (dual == null) dual = findNode(root, "Dual Translate v2", true);\n        if (dual == null) dual = findNode(root, "Dual Translate v3", true);\n        if (dual != null) {\n            if (clickNodeOrParent(dual)) {\n                actionCooldownUntil = now + 3200;\n                saveDiagnostic("Automatic selected-text action: clicked Dual Translate. Waiting for Android to deliver the selected phrase.");\n                return true;\n            }\n        }\n\n        // ElevenReader uses a custom selection toolbar. It exposes Copy / Select all /\n        // Add pronunciation, but not the selected character range. For ElevenReader only,\n        // wait for the toolbar to settle, click Copy automatically, then briefly focus a\n        // transparent activity so Android allows this app to read the copied selection.\n        if (now < elevenReaderSeenUntil) {\n            AccessibilityNodeInfo erCopy = findNode(root, "Copy", true);\n            AccessibilityNodeInfo erSelectAll = findNode(root, "Select all", true);\n            AccessibilityNodeInfo erPronunciation = findNode(root, "Add pronunciation", true);\n            boolean elevenToolbar = erCopy != null && erSelectAll != null && erPronunciation != null;\n            if (elevenToolbar) {\n                if (elevenToolbarFirstSeen == 0) {\n                    elevenToolbarFirstSeen = now;\n                    saveDiagnostic("ElevenReader custom selection toolbar detected. Waiting briefly for selection handles to settle.");\n                    handler.postDelayed(this::scanForSelectionUi, 520);\n                    return true;\n                }\n                if (now - elevenToolbarFirstSeen >= 430 && now >= copyFallbackCooldownUntil) {\n                    if (clickNodeOrParent(erCopy)) {\n                        copyFallbackCooldownUntil = now + 4200;\n                        actionCooldownUntil = now + 900;\n                        elevenToolbarFirstSeen = 0;\n                        saveDiagnostic("ElevenReader fallback: selected phrase copied automatically. Capturing it for translation.");\n                        handler.postDelayed(this::launchClipboardCapture, 160);\n                        return true;\n                    }\n                }\n            } else if (elevenToolbarFirstSeen != 0 && now - elevenToolbarFirstSeen > 2200) {\n                elevenToolbarFirstSeen = 0;\n            }\n        }\n\n'''
if needle not in s:
    raise RuntimeError('Selection service patch anchor not found')
s = s.replace(needle, insert)
anchor = '    private AccessibilityNodeInfo findNode(AccessibilityNodeInfo root, String wanted, boolean exact) {'
method = '''    private void launchClipboardCapture() {\n        try {\n            Intent i = new Intent(this, ClipboardCaptureActivity.class);\n            i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_NO_ANIMATION | Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);\n            startActivity(i);\n        } catch (Exception e) {\n            saveDiagnostic("ElevenReader clipboard capture could not start: " + e.getClass().getSimpleName() + ": " + String.valueOf(e.getMessage()));\n        }\n    }\n\n'''
s = s.replace(anchor, method + anchor)
s = s.replace('Open Dual Translate v2 and add your Google Cloud Translation API key.', 'Open Dual Translate v3 and add your Google Cloud Translation API key.')
s = s.replace('v2 service connected. Waiting for selection. Direct selection + Process Text + Share fallback are enabled for all apps.', 'v3 service connected. Standard selection is enabled for all apps; ElevenReader also uses an automatic Copy capture fallback.')
svc.write_text(s)

cap = root/'app/src/main/java/lt/skarda/dualtranslate/ClipboardCaptureActivity.java'
cap.write_text('''package lt.skarda.dualtranslate;\n\nimport android.app.Activity;\nimport android.content.ClipData;\nimport android.content.ClipboardManager;\nimport android.os.Bundle;\nimport android.os.Handler;\nimport android.os.Looper;\n\npublic class ClipboardCaptureActivity extends Activity {\n    private final Handler handler = new Handler(Looper.getMainLooper());\n    private int attempts;\n\n    @Override\n    protected void onCreate(Bundle savedInstanceState) {\n        super.onCreate(savedInstanceState);\n        getWindow().setDimAmount(0f);\n    }\n\n    @Override\n    protected void onResume() {\n        super.onResume();\n        attempts = 0;\n        handler.postDelayed(this::readCopiedSelection, 60);\n    }\n\n    private void readCopiedSelection() {\n        attempts++;\n        try {\n            ClipboardManager cm = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);\n            ClipData clip = cm == null ? null : cm.getPrimaryClip();\n            if (clip != null && clip.getItemCount() > 0) {\n                CharSequence cs = clip.getItemAt(0).coerceToText(this);\n                String text = cs == null ? "" : cs.toString().trim();\n                if (!text.isEmpty()) {\n                    SelectionTranslateService.submitExternalSelection(text, "ElevenReader automatic Copy fallback");\n                    finishWithoutAnimation();\n                    return;\n                }\n            }\n        } catch (Exception ignored) {\n        }\n        if (attempts < 7) handler.postDelayed(this::readCopiedSelection, 80);\n        else finishWithoutAnimation();\n    }\n\n    private void finishWithoutAnimation() {\n        handler.removeCallbacksAndMessages(null);\n        finish();\n        overridePendingTransition(0, 0);\n    }\n\n    @Override\n    protected void onDestroy() {\n        handler.removeCallbacksAndMessages(null);\n        super.onDestroy();\n    }\n}\n''')

manifest = root/'app/src/main/AndroidManifest.xml'
m = manifest.read_text()
m = m.replace('android:label="Dual Translate v2"', 'android:label="Dual Translate v3"')
m = m.replace('        <activity\n            android:name=".TextReceiverActivity"', '        <activity\n            android:name=".ClipboardCaptureActivity"\n            android:exported="false"\n            android:excludeFromRecents="true"\n            android:noHistory="true"\n            android:theme="@style/TransparentReceiverTheme" />\n\n        <activity\n            android:name=".TextReceiverActivity"')
manifest.write_text(m)

build = root/'app/build.gradle'
b = build.read_text().replace("applicationId 'lt.skarda.dualtranslate.v2'", "applicationId 'lt.skarda.dualtranslate.v3'")
b = b.replace('versionCode 2', 'versionCode 3').replace("versionName '2.0'", "versionName '3.0'")
build.write_text(b)

main = root/'app/src/main/java/lt/skarda/dualtranslate/MainActivity.java'
ms = main.read_text()
ms = ms.replace('Automatic EN -> Lithuanian + Russian translation for selected text in ElevenReader and other Android apps.', 'Automatic EN -> Lithuanian + Russian translation for selected text. ElevenReader has a dedicated automatic selection fallback.')
ms = ms.replace('Enable "Dual Translate v2" once. Then select an English word or phrase. v2 first reads a normal Android selection event; if the app hides the selection, it automatically invokes the Android Process Text action, with Share as a fallback. No manual Translate/Share tap is required.', 'Enable Dual Translate v3 once. In normal apps it uses Android selected text. In ElevenReader, which uses a custom selection menu, v3 automatically presses Copy and captures the selected phrase. No extra tap is required after selecting.')
ms = ms.replace("The key is stored only in this app's private storage. Cloud Translation must be enabled for the Google Cloud project. No clipboard permission is used.", "The key is stored only in this app's private storage. Cloud Translation must be enabled. Clipboard is used only as an automatic ElevenReader fallback because ElevenReader does not expose its selected range through the normal Android selection API.")
main.write_text(ms)

recv = root/'app/src/main/java/lt/skarda/dualtranslate/TextReceiverActivity.java'
recv.write_text(recv.read_text().replace('Re-enable Dual Translate v2 in Accessibility settings.', 'Re-enable Dual Translate v3 in Accessibility settings.'))

strings = root/'app/src/main/res/values/strings.xml'
strings.write_text(strings.read_text().replace('Dual Translate v2', 'Dual Translate v3'))
